print("Welcome to AksTraL's DMAS calculator")
a= int(input("Enter your first number{a}="))
b= int(input("Enter your second number{b}="))
print("according to the user's input...")
print("a=", a) 
print("b=", b)
print("the sum of",a,"and",b,"is", a+b)
print("the difference of",a,"and",b,"is", a-b)
print("the product of",a,"and",b,"is", a*b)
print("the modulus of",a,"and",b,"is", a/b)
print("The variable type of", a, "is", type(a))
print("The variable type of", b, "is", type(b))
print("Thankyou for using AksTraL's DMAS calculator")
